server:
  port: 8095

logging:
  level:
    root: INFO

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/notification_service
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: update
  sql:
    init:
      platform: postgres
  activemq:
    broker-url: tcp://localhost:61616
    acknowledge_mode: dups_ok
destination:
  events: real-estate-events
  removals: entity-removals