server:
  port: 8095

logging:
  level:
    root: INFO

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:p6spy:postgresql://db:5432/notification_service
    username: postgres
    password: password
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: update
  sql:
    init:
      platform: postgres
  activemq:
    broker-url: tcp://active-mq:61616
    acknowledge_mode: dups_ok
destination:
  events: real-estate-events.que
  removals: entity-removals.que
email:
  properties:
    SMTP_PORT: '465'
    EMAIL_SUBJECT: STAMBENI OGLASNIK - NOTIFIKACIJA
    SMTP_SERVER: mail.brigital.rs
    EMAIL_TO_CC: ''
    PASSWORD: password
    USERNAME: realestate@brigital.rs
    EMAIL_FROM: realestate@brigital.rs