server:
  port: 9000
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://db:5432/auth_server
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: update
  sql:
    init:
      platform: postgres
logging:
  level:
    root: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
email:
  properties:
    SMTP_PORT: '465'
    EMAIL_SUBJECT: STAMBENI OGLASNIK
    SMTP_SERVER: mail.brigital.rs
    EMAIL_TO_CC: ''
    PASSWORD: password
    USERNAME: realestate@brigital.rs
    EMAIL_FROM: realestate@brigital.rs